-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 11:50:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nfactoryblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nfactoryblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nfactoryblog` DEFAULT CHARACTER SET utf8 ;
USE `nfactoryblog` ;

-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_ROLES` (
  `idT_ROLES` INT NOT NULL AUTO_INCREMENT,
  `roles` VARCHAR(45) NULL,
  PRIMARY KEY (`idT_ROLES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_USERS` (
  `idT_USERS` INT NOT NULL AUTO_INCREMENT,
  `MDP` VARCHAR(45) NULL,
  `pseudo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `admin` TINYINT NULL,
  `T_ROLES_idT_ROLES` INT NOT NULL,
  PRIMARY KEY (`idT_USERS`, `T_ROLES_idT_ROLES`),
  INDEX `fk_T_USERS_T_ROLES1_idx` (`T_ROLES_idT_ROLES` ASC),
  CONSTRAINT `fk_T_USERS_T_ROLES1`
    FOREIGN KEY (`T_ROLES_idT_ROLES`)
    REFERENCES `nfactoryblog`.`T_ROLES` (`idT_ROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_ARTICLES` (
  `idT_ARTICLES` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(40) NULL,
  `contenu` LONGTEXT NULL,
  `soustitre` VARCHAR(40) NULL,
  `date` DATE NULL,
  `image` VARCHAR(120) NULL,
  `categorie` VARCHAR(45) NULL,
  `statut` VARCHAR(45) NULL,
  `affichage` TINYINT NULL,
  PRIMARY KEY (`idT_ARTICLES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_COMMENTAIRES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_COMMENTAIRES` (
  `idT_COMMENTAIRES` INT NOT NULL AUTO_INCREMENT,
  `T_USERS_idT_USERS` INT NOT NULL,
  `commentaire` VARCHAR(250) NULL,
  `date` DATE NULL,
  `T_ARTICLES_idT_ARTICLES` INT NOT NULL,
  `affichage` TINYINT NULL,
  PRIMARY KEY (`idT_COMMENTAIRES`, `T_USERS_idT_USERS`, `T_ARTICLES_idT_ARTICLES`),
  INDEX `fk_T_COMMENTAIRES_T_ARTICLES1_idx` (`T_ARTICLES_idT_ARTICLES` ASC),
  CONSTRAINT `fk_T_COMMENTAIRES_T_ARTICLES1`
    FOREIGN KEY (`T_ARTICLES_idT_ARTICLES`)
    REFERENCES `nfactoryblog`.`T_ARTICLES` (`idT_ARTICLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_CATEGORIES` (
  `idT_CATEGORIES` INT NOT NULL AUTO_INCREMENT,
  `photographie` TINYINT NULL,
  `cuisine` TINYINT NULL,
  `sport` TINYINT NULL,
  `fashion` TINYINT NULL,
  PRIMARY KEY (`idT_CATEGORIES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_CATEGORIES_has_T_ARTICLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_CATEGORIES_has_T_ARTICLES` (
  `T_CATEGORIES_idT_CATEGORIES` INT NOT NULL,
  `T_ARTICLES_idT_ARTICLES` INT NOT NULL,
  `motscles` VARCHAR(45) NULL,
  PRIMARY KEY (`T_CATEGORIES_idT_CATEGORIES`, `T_ARTICLES_idT_ARTICLES`),
  INDEX `fk_T_CATEGORIES_has_T_ARTICLES_T_ARTICLES1_idx` (`T_ARTICLES_idT_ARTICLES` ASC),
  INDEX `fk_T_CATEGORIES_has_T_ARTICLES_T_CATEGORIES1_idx` (`T_CATEGORIES_idT_CATEGORIES` ASC),
  CONSTRAINT `fk_T_CATEGORIES_has_T_ARTICLES_T_CATEGORIES1`
    FOREIGN KEY (`T_CATEGORIES_idT_CATEGORIES`)
    REFERENCES `nfactoryblog`.`T_CATEGORIES` (`idT_CATEGORIES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_CATEGORIES_has_T_ARTICLES_T_ARTICLES1`
    FOREIGN KEY (`T_ARTICLES_idT_ARTICLES`)
    REFERENCES `nfactoryblog`.`T_ARTICLES` (`idT_ARTICLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfactoryblog`.`T_COMMENTAIRES_has_T_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nfactoryblog`.`T_COMMENTAIRES_has_T_USERS` (
  `T_COMMENTAIRES_idT_COMMENTAIRES` INT NOT NULL,
  `T_COMMENTAIRES_T_USERS_idT_USERS` INT NOT NULL,
  `T_COMMENTAIRES_T_ARTICLES_idT_ARTICLES` INT NOT NULL,
  `T_USERS_idT_USERS` INT NOT NULL,
  PRIMARY KEY (`T_COMMENTAIRES_idT_COMMENTAIRES`, `T_COMMENTAIRES_T_USERS_idT_USERS`, `T_COMMENTAIRES_T_ARTICLES_idT_ARTICLES`, `T_USERS_idT_USERS`),
  INDEX `fk_T_COMMENTAIRES_has_T_USERS_T_USERS1_idx` (`T_USERS_idT_USERS` ASC),
  INDEX `fk_T_COMMENTAIRES_has_T_USERS_T_COMMENTAIRES1_idx` (`T_COMMENTAIRES_idT_COMMENTAIRES` ASC, `T_COMMENTAIRES_T_USERS_idT_USERS` ASC, `T_COMMENTAIRES_T_ARTICLES_idT_ARTICLES` ASC),
  CONSTRAINT `fk_T_COMMENTAIRES_has_T_USERS_T_COMMENTAIRES1`
    FOREIGN KEY (`T_COMMENTAIRES_idT_COMMENTAIRES` , `T_COMMENTAIRES_T_USERS_idT_USERS` , `T_COMMENTAIRES_T_ARTICLES_idT_ARTICLES`)
    REFERENCES `nfactoryblog`.`T_COMMENTAIRES` (`idT_COMMENTAIRES` , `T_USERS_idT_USERS` , `T_ARTICLES_idT_ARTICLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_COMMENTAIRES_has_T_USERS_T_USERS1`
    FOREIGN KEY (`T_USERS_idT_USERS`)
    REFERENCES `nfactoryblog`.`T_USERS` (`idT_USERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
